# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 'COMP 285'
tagline: 'Algorithm Foundations for AI and Cyber-security'
description: 'North Carolina A&T University, Spring 2022'
author: Luis A. Perez
baseurl: '/algorithms-course' # the subpath of your site, e.g. /blog
url: 'https://kandluis.github.io' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
ga_tracking: G-87Q4Z33975

# Theme settings
remote_theme: pmarsceill/just-the-docs@v0.3.3
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  Blackboard:
    - 'https://blackboard.ncat.edu/webapps/blackboard/execute/modulepage/view?course_id=_3567742_1'
  Piazza:
    - 'https://piazza.com/north_carolina_at_state_university/spring2022/comp285/home'
  Gradescope:
    - 'https://www.gradescope.com/courses/350304'
  Zoom:
    - 'https://ncat.zoom.us/s/99432621515?pwd=WmNzUWp4N1liSGZzWTBrQWZOMUlhZz09'
  Feedback:
    - 'https://forms.office.com/r/Z2dBW4Xn2L'

aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content:

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
  lectures:
  homework:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      subpath: '/assets/images/'
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement
  - scope:
      path: ''
      type: lectures
    values:
      layout: lecture
  - scope:
      path: ''
      type: homework
    values:
      layout: homework

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

plugins:
  - jekyll-seo-tag
